version: '3.8'

services:
  # FlareSolverr服务 - CF绕过
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: midjourney-flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Asia/Shanghai
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - midjourney-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/v1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Midjourney Mirror主应用
  midjourney-mirror:
    build: .
    container_name: midjourney-mirror-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - FLARESOLVERR_ENABLED=true
      - TEST_MODE=false
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-docker
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - LOG_LEVEL=info
      - MIDJOURNEY_BASE_URL=https://www.midjourney.com
      - MIDJOURNEY_API_URL=https://api.midjourney.com
    ports:
      - "3000:3000"
    depends_on:
      flaresolverr:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - midjourney-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  midjourney-network:
    driver: bridge

volumes:
  midjourney-logs:
    driver: local